---
- hosts: shop.das-labor.sexy
  vars:
    - admin_passwd: "smashthestate"
    - dbase_passwd: "bionicman"
  roles:
    - role: magento
      backend_port: 9000
      domain: shop.das-labor.sexy
      dbase_passwd: "{{ dbase_passwd }}"
      admin_email: seu@das-labor.org
      admin_passwd: "{{ admin_passwd }}"
